### ISSUE TITLE
Approx release date-Reg

### ISSUE THREAD

**Issue by aswinkumar2019** [opendatacam/opendatacam-deepstream#1]
Hello Guys,
                  I tried to run yolo v3 model in jetson tx2 but,the memory is full within 20mins at 5fps speed.
Guys i am in need of this project.Please give the approximate release date for this update.

I am working on a extension project of opendatacam using opendatacam api.
Will the new update affect the old api?
Regards,
Aswin Kumar

**Comment by tdurand** [comment]
hi, there is a work in progress published: https://github.com/opendatacam/opendatacam-deepstream , we don't have any dates / guarantee it will work right now. The goal is not to touch to the API
