### ISSUE TITLE
Deepstream patch, error while making nvdsinfer

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam-deepstream#6]
Platform: Jetson nano
Jetpack 4.3 [L4T 32.3.1]
OpenCV 4.1.1 

When I try to follow the deepstream patch: https://github.com/AtosInnovationBordeaux/opendatacam-deepstream/tree/master/deepstream_patch  and reach the part I need to compile again nvdsinfer, I get this error:

```
In file included from nvdsinfer_context_impl.cpp:22:0:
nvdsinfer_context_impl.h:25:10: fatal error: opencv2/objdetect/objdetect.hpp: No such file or directory
```

Full output

```
nvidia@nvidia:/opt/nvidia/deepstream/deepstream-4.0/sources/libs/nvdsinfer$ sudo CUDA_VER=10.0 make
-fPIC -std=c++11 -I /usr/local/cuda-10.0/include -I ../../includes
g++ -c -o nvdsinfer_context_impl.o -fPIC -std=c++11 -I /usr/local/cuda-10.0/include -I ../../includes nvdsinfer_context_impl.cpp
In file included from nvdsinfer_context_impl.cpp:22:0:
nvdsinfer_context_impl.h:25:10: fatal error: opencv2/objdetect/objdetect.hpp: No such file or directory
 #include <opencv2/objdetect/objdetect.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:47: recipe for target 'nvdsinfer_context_impl.o' failed
```

@anasBahou any idea ? Which version on jetpack were you on when working on this ?

cc @b-g

**Comment by tdurand** [comment]
PS: I have installed `sudo apt-get install libopencv-dev`

**Comment by prat96** [comment]
Have you tried configuring the flags?

pkg-config --libs --cflags opencv

**Comment by anasBahou** [comment]
@tdurand I'm on Jetson Nano | JetPack 4.3 | OpenCV 3.4.3
I'm using [this ](https://github.com/opendatacam/opendatacam/blob/master/documentation/USE_WITHOUT_DOCKER.md#1-install-opencv-343-with-gstreamer) to install opencv.

**Comment by tdurand** [comment]
@prat96 yes tried

@anasBahou Ok  that is what I was suspecting, I need to downgrade opencv

**Comment by AtosInnovationBordeaux** [comment]
@tdurand Did it work ?
I forgot to mention that the deepstream [configuration file](https://github.com/opendatacam/opendatacam-deepstream/blob/master/deepstream_patch/deepstream_app_config_yoloV3_tiny_http_rtsp.txt) is set for a single CSI camera stream input and RTSP output

**Comment by tdurand** [comment]
Yes I was able to run it just a few moments ago. I didn't yet recompile with the confidence score, but I was able to run everything without it also. Amazing contribution and very well documented to get started with Deepstream.

Have you been able to also put this into a Docker image easily ?

**Comment by AtosInnovationBordeaux** [comment]
> Have you been able to also put this into a Docker image easily ?

I haven't tried yet. I'm working on extracting the tracking process from ODC to DeepStream. This way, we can replace "node-moving-things-tracker" with DeepStream tracker to improve tracking accuracy.
