### ISSUE TITLE
"node-gyp rebuild" error

### ISSUE THREAD

**Issue by anasBahou** [opendatacam/opendatacam-deepstream#9]
Hi,

I'm having some issues with buffertools(node module) while installing opendatacam on the jetson nano with Jetpack 4.4.

Here is my configuration:
node version: v12.18.2
gcc version: 7.5.0

I've already tried removing "node_modules" folder and package-lock.json file + retried npm install BUT it doesn't seem to work. (See the error_log file)

Can anyone help?
cc @tdurand @thepycoder 

Thanks,
[error_log.txt](https://github.com/opendatacam/opendatacam-deepstream/files/4931576/error_log.txt)

**Comment by tdurand** [comment]
Hi

There is an issue with buffertools and node v12

I removed the dependency a while ago: https://github.com/opendatacam/opendatacam/commit/2be0907cd9c1cec48c84e300a4dc54a03f841148 , please use latest master

Otherwise need to use node v10

**Comment by anasBahou** [comment]
Thanks a lot @tdurand 

Downgrading Node to v10 fixed it.
